class_based_view/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    #basic_app:list is referred by basic_app_base.html
    url(r'^$', views.SchoolListView.as_view(), name='list'),
    #below regular expression says to take the basic_app domain extension page
    #and use the <pk> primary key and take that as school's detail view
    url(r'^(?P<pk>\d+)/$', views.SchoolDetailView.as_view(), name='detail'),
    url(r'^create/$', views.SchoolCreateView.as_view(), name='create'),
    url(r'^update/(?P<pk>\d+)/$', views.SchoolUpdateView.as_view(), name='update'),
    url(r'^delete/(?P<pk>\d+)/$', views.SchoolDeleteView.as_view(), name='delete'),
]

class_based_view/class_based_view/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from basic_app import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view()),
    url(r'^admin/', admin.site.urls),
    url(r'^basic_app/', include('basic_app.urls', namespace='basic_app')),
]

class_based_view/basic_app/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        #detail is coming from the urls.py defined for the school details endpoint
        #pass in the primary key
        return reverse('basic_app:detail', kwargs={'pk': self.pk})

class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School, related_name='students')

    def __str__(self):
        return self.name

class_based_view/basic_app/views.py
from django.shortcuts import render
from django.views.generic import (
    View, TemplateView, ListView, DetailView, CreateView, UpdateView,
    DeleteView
)
from django.http import HttpResponse
from basic_app import models
from django.core.urlresolvers import reverse_lazy

# Create your views here.
#instead of defining function below, we will create class based view
# Method 1: using a function and rendering a template
# def index(request):
#     return render(request, 'basic_app/index.html')

# Method 2: using a class based view and rendering a HttpResponse
class CBView(View):
    def get(self, request):
        return HttpResponse('CLASS BASED VIEWS ARE WAY COOL!!')

# Method 3: using a templateView
class IndexView(TemplateView):
    template_name = 'basic_app/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['inject_me'] = 'BASIC INJECTION'
        return context

class SchoolListView(ListView):
    context_object_name = 'schools'
    model = models.School
    #The ListView will return by default school_list(It will lowercase
    # the name of the model (in this case school) and appends _list)
    # If you want to override this name provide the context_object_name

class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.School
    template_name = 'basic_app/school_detail.html'
    # The DetailView will return by default the model name in lowercase
    # in our case school. If you want to override this name provide
    # the context_object_name

class SchoolCreateView(CreateView):
    fields = ('name', 'principal', 'location')
    model = models.School

class SchoolUpdateView(UpdateView):
    fields = ('name', 'principal')
    model = models.School

class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy('basic_app:list')

class_based_view/basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'basic_app:list' %}">Schools</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="#"></a></li>
        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>
  </body>
</html>

class_based_view/basic_app/templates/basic_app/school_confirm_delete.html
{% extends 'basic_app/basic_app_base.html' %}
{% block body_block %}
  <h1>Delete {{ school.name }}?</h1>
  <form method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Delete">
    <a href="{% url 'basic_app:detail' pk=school.pk %}">Cancel</a>
  </form>
{% endblock %}

class_based_view/basic_app/templates/basic_app/school_detail.html
{% extends 'basic_app/basic_app_base.html' %}

{% block body_block %}
<div class="jumbotron">
  <h1>Welcome to school details page</h1>
  <h2>School details:</h2>
  <p>Name: {{school_detail.name}}</p>
  <p>Principal: {{school_detail.principal}}</p>
  <p>Location: {{school_detail.location}}</p>
  <h3>Students</h3>
  <!-- Note:students name comes from the models where we defined it
  as foreign key with a related name -->
  {% for student in school_detail.students.all %}
    <p>{{student.name}} who is {{student.age}} years old.</p>
  {% endfor %}
</div>
<div class="container">
  <p><a class="btn btn-warning" href="{% url 'basic_app:update' pk=school_detail.pk %}">Update</a></p>
</div>
{% endblock %}

class_based_view/basic_app/templates/basic_app/school_form.html
{% extends 'basic_app/basic_app_base.html' %}
{% block body_block %}
<h1>
  {% if not form.instance.pk %}
    Create School
  {% else %}
    Update School
  {% endif %}
</h1>

<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" class="btn btn-primary" value="Submit">
</form>

{% endblock %}

class_based_view/basic_app/templates/basic_app/school_list.html
{% extends 'basic_app/basic_app_base.html' %}

{% block body_block %}
<h1>Welcome to a list of all schools</h1>
<ol>
  {% for school in schools %}
  <h2><li><a href="{{school.id}}">{{ school.name }}</a></li></h2>
  {% endfor %}
</ol>
{% endblock %}

class_based_view/templates/basic_app/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'basic_app:list' %}">Schools</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="#"></a></li>
        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>
  </body>
</html>

class_based_view/templates/basic_app/index.html
{% extends "basic_app/base.html" %}
{% block body_block %}
<div class="jumbotron">
  <h1>HOME PAGE</h1>
</div>
{% endblock %}